source 'https://rubygems.org'

gem 'aasm'
gem 'activesupport'
gem 'brewery_db'
gem 'capistrano', '~> 3.3.0'
gem 'cinch', github: 'CoralineAda/cinch', branch: 'nick_change_user_fix'
gem 'database_cleaner', '~> 1.3.0', group: :test #s :github => 'bmabey/database_cleaner', group: :test
gem 'dotenv'
gem 'google-search', '~> 1.0'
gem 'inflections'
gem 'marky_markov'
gem 'mongoid', '~> 3.1.6'
gem 'poro_plus'
gem 'pry'
gem 'raad'
gem 'rake'
gem 'require_all'
gem 'rspec', :group => :test
gem 'ruby-stemmer', '>=0.8.3', require: 'lingua/stemmer'
gem 'rubyfish'
gem 'sanitize', '>= 3.0.2'
gem 'wikipedia-client'
gem 'yummly'

