source 'https://rubygems.org'

gem 'aasm'
gem 'activesupport'
gem 'brewery_db'
gem 'capistrano'
gem 'database_cleaner', '~> 1.3.0', group: :test #s :github => 'bmabey/database_cleaner', group: :test
gem 'dotenv'
gem 'google-search', '~> 1.0'
gem 'marky_markov'
gem 'mongoid', '~> 6.0.0'
gem 'nokogiri'
gem 'octokit', '~> 3.0'
gem 'poro_plus'
gem 'pry'
gem 'rake'
gem 'require_all'
gem 'rspec', :group => :test
gem 'ruby-stemmer', '>=0.8.3', require: 'lingua/stemmer'
gem 'rubyfish'
gem 'sanitize', '>= 3.0.2'
gem 'sinatra'
gem 'slackbotsy'
gem 'wikipedia-client', ">= 1.4.0"
gem 'wolfram-alpha'
gem 'yummly'
